- hosts: all
  vars_files:
    - /var/ansible/vars/users.yml

  tasks:
  - name: "Create user accounts and add users to groups"
    user:
      name: "{{ item }}"
      groups: "admin,www-data"
    with_items: "{{ users }}"
    delegate_to: ansible-awx.voice.hr.asseco-see.local
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', '/var/ansible/keys/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"
    delegate_to: ansible-awx.voice.hr.asseco-see.local
