- hosts: all
  tasks:
    - name: Transfer file from central server to the rest
      synchronize:
        src: /var/transport_files/
        dest: /live/update/
      delegate_to: ansible-awx.voice.hr.asseco-see.local
